<html>
	<head><title>DATABASE log in</title></head>
	<body>

	<h1>LIBRARY MANAGEMENT SYSTEM</h1>
	<form  method="post">

	<a href="home.php" ><input type="button" Value="home"></a>
	<a href="#abt" ><input type="button" Value="about"></a>
	<a href="#ftr" ><input type="button" Value="feature"></a>
	<a href="#cnt" ><input type="button" Value="contact us"></a>
	
	<a href="sign.php"><input type="button" Value="sign up/sign in"></a>
	<a href="home_lib.php" ><input type="button" Value="issue/return"></a>
	
	<br><br><br>
	<input type="image" src="l2.jpg" width="100%" height="70%">
	<h3 id="abt">ABOUT</h3>
	this is about section.....this is about section.....this is about section.....this is about sec.this is about section.......this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....
	<h3 id="ftr">FEATURE</h3>
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	<h3 id="cnt">CONTACT US</h3>
	this is contact section......this is contact section......this is contact section......this is contact section......this is contact section......
	this is contact section......this is contact section......this is contact section......this is contact section......this is contact section......
	this is contact section......this is contact section......this is contact section......this is contact section......this is contact section......
	</form>

</body>
</html>