<html>
	<head>
	
	</head>
	<body>
	<h1 align="center">WELCOME TO OUR RESTAURANT</h1>
	<form  method="post">

	<a href="home.php" ><input type="button" Value="home"></a>
	<a href="#abt" ><input type="button" Value="about"></a>
	<a href="#ftr" ><input type="button" Value="feature"></a>
	<a href="course.php"><input type="button" Value="courses"></a>
	<a href="login_c.php" ><input type="button" Value="place order"></a>
	<a href="#cnt" ><input type="button" Value="contact us"></a>
	<br><br><br>
	<input type="image" src="f.jpg" width="100%" height="100%">
	<h3 id="abt">ABOUT</h3>
	this is about section.....this is about section.....this is about section.....this is about sec.this is about section.......this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....this is about section.....
	this is about section.....
	<h3 id="ftr">FEATURE</h3>
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	this is feature section......this is feature section......this is feature section......this is feature section......this is feature section......
	<h3 id="cnt">CONTACT US</h3>
	this is contact section......this is contact section......this is contact section......this is contact section......this is contact section......
	this is contact section......this is contact section......this is contact section......this is contact section......this is contact section......
	this is contact section......this is contact section......this is contact section......this is contact section......this is contact section......
	</form>

	</body>
</html>